---
# tasks file for influxdb (Ubuntu specific)

- name: Download InfluxDB GPG key
  become: yes
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  tags:
    - influxdb

- name: Ensure apt-transport-https is installed
  become: yes
  apt:
    name: apt-transport-https
    state: present
  tags:
    - influxdb

- name: Configure InfluxDB APT repository
  become: yes
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  tags:
    - influxdb

- name: Install InfluxDB packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ influxdb_packages }}"
  tags:
    - influxdb
